name: MineResetLite
version: 1.3.3.7
main: com.koletar.jj.mineresetlite.MineResetLite
author: jjkoletar
description: A lightweight solution for Mine management.
softdepend: [AsyncWorldEdit, Multiverse-Core, HolographicDisplays]
commands:
  mineresetlite:
    aliases: [mrl, mr, mine, minereset]
    description: Manage mines.